export enum CapabilityStatus {
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  AVAILABLE = 'AVAILABLE',
  DEGRADED = 'DEGRADED',
  UNAVAILABLE = 'UNAVAILABLE',
}

export enum SystemCapability {
  DATABASE = 'DATABASE',
  AI_ENGINE = 'AI_ENGINE',
  NEWS_DISCOVERY = 'NEWS_DISCOVERY',
  WEB_RESEARCH = 'WEB_RESEARCH',
  VERIFICATION = 'VERIFICATION',
  EVENT_INTELLIGENCE = 'EVENT_INTELLIGENCE',
  SCORING = 'SCORING',
  EDITORIAL_GENERATION = 'EDITORIAL_GENERATION',
  IMAGE_GENERATION = 'IMAGE_GENERATION',
  PUBLIC_NEWS_PORTAL = 'PUBLIC_NEWS_PORTAL',
  SCHEDULER = 'SCHEDULER',
  EMAIL_DELIVERY = 'EMAIL_DELIVERY',
  FACEBOOK_PUBLISHING = 'FACEBOOK_PUBLISHING',
  INSTAGRAM_PUBLISHING = 'INSTAGRAM_PUBLISHING',
}

export enum AutonomyLevel {
  LEVEL_0 = 'LEVEL_0',
  LEVEL_1 = 'LEVEL_1',
  LEVEL_2 = 'LEVEL_2',
  LEVEL_3 = 'LEVEL_3',
  LEVEL_4 = 'LEVEL_4',
  LEVEL_5 = 'LEVEL_5',
}

export enum SystemMode {
  NORMAL = 'NORMAL',
  READ_ONLY = 'READ_ONLY',
  MAINTENANCE = 'MAINTENANCE',
  EMERGENCY_STOP = 'EMERGENCY_STOP',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum VerificationStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  PARTIALLY_VERIFIED = 'PARTIALLY_VERIFIED',
  UNVERIFIED = 'UNVERIFIED',
  CONTRADICTED = 'CONTRADICTED',
  FAILED = 'FAILED',
}

export enum VerificationConfidence {
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}

export enum ContentCategory {
  AI = 'AI',
  TECH = 'TECH',
  SOLAR = 'SOLAR',
  ENERGY = 'ENERGY',
  ROBOTICS = 'ROBOTICS',
  AUTOMATION = 'AUTOMATION',
  CYBERSECURITY = 'CYBERSECURITY',
  SOFTWARE = 'SOFTWARE',
  HARDWARE = 'HARDWARE',
  SCIENCE = 'SCIENCE',
  STARTUPS = 'STARTUPS',
  SPACE = 'SPACE',
  FUTURE_TECH = 'FUTURE_TECH',
}

export enum NewsStatus {
  INGESTED = 'INGESTED',
  VERIFYING = 'VERIFYING',
  VERIFIED = 'VERIFIED',
  SCORED = 'SCORED',
  CANDIDATE = 'CANDIDATE',
  DRAFTING = 'DRAFTING',
  DRAFT_READY = 'DRAFT_READY',
  VISUAL_READY = 'VISUAL_READY',
  READY_FOR_REVIEW = 'READY_FOR_REVIEW',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  DUPLICATE = 'DUPLICATE',
  UNVERIFIED = 'UNVERIFIED',
  EXPIRED = 'EXPIRED',
  FAILED = 'FAILED',
  BLOCKED = 'BLOCKED',
  CANCELLED = 'CANCELLED',
}

export enum NewsPriority {
  IGNORE = 'IGNORE',
  ARCHIVE = 'ARCHIVE',
  LOW = 'LOW',
  CANDIDATE = 'CANDIDATE',
  HIGH = 'HIGH',
  TOP = 'TOP',
}

export enum SourceType {
  OFFICIAL = 'OFFICIAL',
  PRIMARY_MEDIA = 'PRIMARY_MEDIA',
  SECONDARY_MEDIA = 'SECONDARY_MEDIA',
  GOVERNMENT = 'GOVERNMENT',
  ACADEMIC = 'ACADEMIC',
  COMPANY_BLOG = 'COMPANY_BLOG',
  PRESS_RELEASE = 'PRESS_RELEASE',
  SOCIAL_OFFICIAL = 'SOCIAL_OFFICIAL',
  SOCIAL_UNVERIFIED = 'SOCIAL_UNVERIFIED',
  COMMUNITY = 'COMMUNITY',
  BLOG = 'BLOG',
  AGGREGATOR = 'AGGREGATOR',
  UNKNOWN = 'UNKNOWN',
}

export enum SourceCredibilityBand {
  UNKNOWN = 'UNKNOWN',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  AUTHORITATIVE = 'AUTHORITATIVE',
}
